[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && npm run db:init --workspace=server"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
